### ISSUE TITLE
Refactor code to have several files

### ISSUE THREAD

**Issue by jesi-rgb** [nipunramk/Video-Dev#8]
Basically I am wondering if we could migrate some of the functions we are using to a file like `functions.py` or `utils.py`, as well as the new classes like `BarChart` or `ImageUtils` to a `classes.py` files.

The motivation behind it is the file length is getting pretty long and even with code folding I am having a hard time sometimes finding what I am searching for. It is really a very small, minor thing, but maybe could be cool and would not take much time at all.

Let me know your thoughts!

**Comment by nipunramk** [comment]
Good idea to do a refactor and make sure all necessary modules are imported to the "main" file. Feel free to add a PR with it, I'll run through and make sure there is nothing breaking on my side.
